name: Isaac Simulation CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ROS 2 Humble
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions python3-pip
        pip3 install -U setuptools

    - name: Install ROS 2 dependencies
      run: |
        sudo apt install software-properties-common
        sudo add-apt-repository universe
        sudo apt update && sudo apt install curl -y
        export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
        curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" # If using Ubuntu derivates use $UBUNTU_CODENAME
        sudo apt install /tmp/ros2-apt-source.deb
        sudo apt update
        sudo apt upgrade
        sudo apt install ros-humble-desktop
        sudo apt install ros-dev-tools
        source /opt/ros/humble/setup.bash
        rosdep update
        rosdep install --from-paths . --ignore-src -r -y

    - name: Build workspace
      run: |
        colcon build --base-paths . --event-handlers console_direct+

    - name: Run tests
      run: |
        colcon test --base-paths .
        colcon test-result --verbose
